import { redirect } from "next/navigation";

/**
 * The platform's marketing content now lives at the site root (see
 * app/page.tsx) — this route just keeps old /platform links/bookmarks
 * working via a redirect rather than a dead 404. Forwards the query
 * string (notably `?ref=`) — every referral link generated by
 * features/admin/referrals/referral-manager.tsx still points at
 * /platform?ref=..., and a bare `redirect("/")` was silently dropping
 * `ref`, so referral visits were never actually being logged (see
 * app/page.tsx's logReferralVisit call).
 */
export default async function PlatformRedirectPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const qs = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") qs.set(key, value);
  }
  const suffix = qs.toString();
  redirect(suffix ? `/?${suffix}` : "/");
}
